version: "3.9"
services:
    node:
        build:
            context: .
            dockerfile: ./Dockerfile
        working_dir: /app
        container_name: code-katas
        volumes:
            - .:/app
        command: ["sleep", "infinity"]
